# CRMLS Listing Data Analysis

In [1]:
import pandas as pd
import glob

In [2]:
# Get all CRMLSListing files
sold_data = glob.glob('**/CRMLSListing*.csv', recursive=True)

df_list = []
for file in sold_data:
    df = pd.read_csv(file, encoding='ISO-8859-1',low_memory=True)
    df_list.append(df)
listings_df = pd.concat(df_list, ignore_index=True)

## Data Exploration

In [3]:
listings_df.head()

,OriginalListPrice,ListingKey,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,PropertyType,...,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1,ListAgentEmail,BuyerAgencyCompensationType,BuyerAgencyCompensation
0,1775000.0,1156313594,NaN,NaN,Diana,Trinh-Salzer,34.181456,-119.232985,4575 Gateshead Bay,Residential,...,NaN,93035,NaN,NaN,2800.0,NaN,4575 Gateshead Bay,NaN,NaN,NaN
1,2900000.0,1156305330,2026-03-12,2900000.0,Molly,Fleming,32.988714,-117.263012,618 Sonrisa St.,Residential,...,San Dieguito Union,92075,Compass,0.0,11200.0,NaN,618 Sonrisa St.,NaN,NaN,NaN
2,519000.0,1156298355,NaN,NaN,Hans,Hagenmayer,34.258190,-118.326305,8780 1/2 Wyngate Street,Residential,...,NaN,91040,NaN,681.0,299257.2,NaN,8780 1/2 Wyngate Street,NaN,NaN,NaN
3,4698000.0,1156294964,NaN,NaN,Robyn,Robinson,33.504678,-117.638115,31445 Juliana Farms Road,Residential,...,Capistrano Unified,92675,NaN,535.0,26702.0,NaN,31445 Juliana Farms Road,NaN,NaN,NaN
4,1100000.0,1156294960,2026-03-17,1100000.0,Hamid,Koochak,34.016973,-118.368336,5625 Aladdin Street,Residential,...,NaN,90008,Compass,320.0,13225.0,NaN,5625 Aladdin Street,NaN,NaN,NaN

In [4]:
# Look at dataframe columns
listings_df.columns

Index(['OriginalListPrice', 'ListingKey', 'CloseDate', 'ClosePrice',
       'ListAgentFirstName', 'ListAgentLastName', 'Latitude', 'Longitude',
       'UnparsedAddress', 'PropertyType', 'LivingArea', 'ListPrice',
       'DaysOnMarket', 'ListOfficeName', 'BuyerOfficeName', 'CoListOfficeName',
       'ListAgentFullName', 'CoListAgentFirstName', 'CoListAgentLastName',
       'BuyerAgentMlsId', 'BuyerAgentFirstName', 'BuyerAgentLastName',
       'FireplacesTotal', 'AssociationFeeFrequency', 'AboveGradeFinishedArea',
       'ListingKeyNumeric', 'MLSAreaMajor', 'TaxAnnualAmount',
       'CountyOrParish', 'PropertyType.1', 'MlsStatus', 'ElementarySchool',
       'ListAgentFirstName.1', 'AttachedGarageYN', 'ParkingTotal',
       'BuilderName', 'PropertySubType', 'LotSizeAcres', 'SubdivisionName',
       'BuyerOfficeAOR', 'YearBuilt', 'DaysOnMarket.1', 'StreetNumberNumeric',
       'LivingArea.1', 'ListingId', 'BathroomsTotalInteger', 'City', 'TaxYear',
       'BuildingAreaTotal', 'BedroomsTotal', 'ContractStatusChangeDate',
       'Longitude.1', 'ElementarySchoolDistrict', 'CoBuyerAgentFirstName',
       'PurchaseContractDate', 'ListingContractDate', 'BelowGradeFinishedArea',
       'BusinessType', 'Latitude.1', 'ListPrice.1', 'StateOrProvince',
       'CoveredSpaces', 'MiddleOrJuniorSchool', 'FireplaceYN', 'Stories',
       'HighSchool', 'Levels', 'ListAgentLastName.1', 'CloseDate.1',
       'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'BuyerOfficeName.1', 'AssociationFee', 'LotSizeSquareFeet',
       'MiddleOrJuniorSchoolDistrict', 'UnparsedAddress.1', 'ListAgentEmail',
       'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'],
      dtype='str')

In [5]:
# Look at statistics of numerical columns
listings_df.describe()

,OriginalListPrice,ListingKey,ClosePrice,Latitude,Longitude,LivingArea,ListPrice,DaysOnMarket,FireplacesTotal,AboveGradeFinishedArea,...,ListPrice.1,CoveredSpaces,Stories,LotSizeArea,MainLevelBedrooms,GarageSpaces,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,BuyerAgencyCompensation
count,7.571020e+05,7.600830e+05,2.052270e+05,654401.000000,655041.000000,6.658030e+05,7.581650e+05,760083.000000,0.0,0.0,...,7.581650e+05,0.0,563709.000000,6.907220e+05,352093.000000,616484.000000,513746.000000,6.897770e+05,0.0,96104.000000
mean,1.047291e+06,1.102442e+09,7.826119e+05,34.517664,-118.362659,3.310118e+03,9.798040e+05,19.294856,NaN,NaN,...,9.798040e+05,NaN,1.368092,6.409633e+04,1.935594,1.758098,204.085416,5.778946e+05,NaN,171.282859
std,6.454594e+06,2.661750e+07,3.660929e+06,1.919514,3.919209,1.114326e+06,2.159951e+06,29.419190,NaN,NaN,...,2.159951e+06,NaN,0.482287,2.146573e+06,5.907915,3.965420,2177.794003,2.377747e+07,NaN,1931.427105
min,0.000000e+00,4.216549e+08,0.000000e+00,-117.472493,-159.523315,0.000000e+00,0.000000e+00,-39.000000,NaN,NaN,...,0.000000e+00,NaN,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,NaN,0.000000
25%,8.000000e+04,1.077602e+09,5.000000e+03,33.757197,-118.516063,1.182000e+03,8.000000e+04,4.000000,NaN,NaN,...,8.000000e+04,NaN,1.000000,4.934000e+03,1.000000,1.000000,0.000000,5.227000e+03,NaN,2.000000
50%,6.390000e+05,1.103156e+09,5.650000e+05,34.051210,-118.091021,1.601000e+03,6.349000e+05,10.000000,NaN,NaN,...,6.349000e+05,NaN,1.000000,7.220000e+03,2.000000,2.000000,0.000000,7.497000e+03,NaN,2.500000
75%,1.150000e+06,1.118548e+09,1.025000e+06,34.297989,-117.287741,2.235000e+03,1.150000e+06,22.000000,NaN,NaN,...,1.150000e+06,NaN,2.000000,1.357075e+04,3.000000,2.000000,309.000000,1.650000e+04,NaN,2.500000
max,1.390000e+09,1.156314e+09,8.200000e+08,737.000000,392.000000,9.090909e+08,4.436503e+08,2539.000000,NaN,NaN,...,4.436503e+08,NaN,2.000000,9.187423e+08,3333.000000,600.000000,968348.000000,7.638115e+09,NaN,187500.000000

In [6]:
# Look at dataframe's dimensions
listings_df.shape

(760083, 84)

In [7]:
# Look at missing values
listings_df.isnull().sum()

OriginalListPrice                 2981
ListingKey                           0
CloseDate                       534132
ClosePrice                      554856
ListAgentFirstName                4487
                                 ...
MiddleOrJuniorSchoolDistrict    760083
UnparsedAddress.1                 1905
ListAgentEmail                    7125
BuyerAgencyCompensationType     663980
BuyerAgencyCompensation         663979
Length: 84, dtype: int64