# CRMLS Sold Data Analysis

In [4]:
import pandas as pd
import glob

## Monthly Dataset Aggregation

In [ ]:
# Get all CRMLSSold files
sold_data = glob.glob('**/CRMLSSold*.csv',recursive=True)

df_list = []
for file in sold_data:
    df = pd.read_csv(file, encoding='ISO-8859-1',low_memory=True)
    print(f"Rows before aggregation: {len(df)}")
    df_list.append(df)
sold_df = pd.concat(df_list, ignore_index=True)

print(f'Rows after aggregation: {len(sold_df)}')

# Filter to residential
print(f"Rows before Residential Filter: {len(sold_df)}")
sold_df = sold_df[sold_df['PropertyType'] == "Residential"]
print(f"Rows after Residential Filter: {len(sold_df)}")

C:\Users\caden\AppData\Local\Temp\ipykernel_21320\3386462130.py:6: DtypeWarning: Columns (0: WaterfrontYN, 1: ElementarySchool, 2: BuilderName, 3: CoBuyerAgentFirstName, 4: PostalCode) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, encoding='ISO-8859-1',low_memory=True)
C:\Users\caden\AppData\Local\Temp\ipykernel_21320\3386462130.py:6: DtypeWarning: Columns (0: WaterfrontYN) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, encoding='ISO-8859-1',low_memory=True)
C:\Users\caden\AppData\Local\Temp\ipykernel_21320\3386462130.py:10: DtypeWarning: Columns (0: WaterfrontYN, 1: ElementarySchool, 2: BuilderName, 3: CoBuyerAgentFirstName, 4: PostalCode) have mixed types. Specify dtype option on import or set low_memory=False.
  print(f'Rows before concat: {sum(len(pd.read_csv(f, encoding="ISO-8859-1")) for f in sold_data)}')
C:\Users\caden\AppData\Local\Temp\ipykernel_21320\3386462130.py:10: DtypeWarning: Columns (0: WaterfrontYN) have mixed types. Specify dtype option on import or set low_memory=False.
  print(f'Rows before concat: {sum(len(pd.read_csv(f, encoding="ISO-8859-1")) for f in sold_data)}')

Rows before concat: 532595
Rows after aggregation: 532595
Rows before Residential Filter: 532595
Rows after Residential Filter: 359471

## Dataset Structuring and Validation

In [6]:
sold_df.head()

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,...,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,OriginatingSystemName,OriginatingSystemSubName,BuyerAgencyCompensationType,BuyerAgencyCompensation,latfilled,lonfilled
0,Mlslistings,Mlslistings,"Carpet,Tile,Wood",True,NaN,NaN,False,499000.0,551985747,jwachter@cbnorcal.com,...,94401,6472.0,NaN,NaN,CRMLS,CRMLS_MLSL,NaN,NaN,NaN,NaN
5,SanDiego,SanDiego,NaN,False,NaN,NaN,False,759900.0,522107581,mdarwich12@gmail.com,...,91950,NaN,NaN,NaN,CRMLS,CRMLS_SAND,NaN,NaN,NaN,NaN
9,SanDiego,SanDiego,NaN,False,NaN,NaN,False,739900.0,510919001,mdarwich12@gmail.com,...,91950,NaN,NaN,NaN,CRMLS,CRMLS_SAND,NaN,NaN,NaN,NaN
28,Mlslistings,Mlslistings,NaN,False,NaN,NaN,NaN,NaN,1079166779,davidmartz@compass.com,...,92262,NaN,13504.0,NaN,CRMLS,CRMLS_MLSL,NaN,NaN,NaN,NaN
29,Southland,Southland,NaN,False,NaN,NaN,False,1890500.0,1075037759,karen.klein@theagencyre.com,...,91356,0.0,17873.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN

In [7]:
# Look at dataframe columns
sold_df.columns

Index(['BuyerAgentAOR', 'ListAgentAOR', 'Flooring', 'ViewYN', 'WaterfrontYN',
       'BasementYN', 'PoolPrivateYN', 'OriginalListPrice', 'ListingKey',
       'ListAgentEmail', 'CloseDate', 'ClosePrice', 'ListAgentFirstName',
       'ListAgentLastName', 'Latitude', 'Longitude', 'UnparsedAddress',
       'PropertyType', 'LivingArea', 'ListPrice', 'DaysOnMarket',
       'ListOfficeName', 'BuyerOfficeName', 'CoListOfficeName',
       'ListAgentFullName', 'CoListAgentFirstName', 'CoListAgentLastName',
       'BuyerAgentMlsId', 'BuyerAgentFirstName', 'BuyerAgentLastName',
       'FireplacesTotal', 'AssociationFeeFrequency', 'AboveGradeFinishedArea',
       'ListingKeyNumeric', 'MLSAreaMajor', 'TaxAnnualAmount',
       'CountyOrParish', 'MlsStatus', 'ElementarySchool', 'AttachedGarageYN',
       'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'StreetNumberNumeric',
       'ListingId', 'BathroomsTotalInteger', 'City', 'TaxYear',
       'BuildingAreaTotal', 'BedroomsTotal', 'ContractStatusChangeDate',
       'ElementarySchoolDistrict', 'CoBuyerAgentFirstName',
       'PurchaseContractDate', 'ListingContractDate', 'BelowGradeFinishedArea',
       'BusinessType', 'StateOrProvince', 'CoveredSpaces',
       'MiddleOrJuniorSchool', 'FireplaceYN', 'Stories', 'HighSchool',
       'Levels', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'AssociationFee', 'LotSizeSquareFeet', 'MiddleOrJuniorSchoolDistrict',
       'OriginatingSystemName', 'OriginatingSystemSubName',
       'BuyerAgencyCompensationType', 'BuyerAgencyCompensation', 'latfilled',
       'lonfilled'],
      dtype='str')

In [8]:
# Look at statistics of numerical columns
sold_df.describe()

,OriginalListPrice,ListingKey,ClosePrice,Latitude,Longitude,LivingArea,ListPrice,DaysOnMarket,FireplacesTotal,AboveGradeFinishedArea,...,BelowGradeFinishedArea,CoveredSpaces,Stories,LotSizeArea,MainLevelBedrooms,GarageSpaces,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,BuyerAgencyCompensation
count,3.588440e+05,3.594710e+05,3.594690e+05,343863.000000,343863.000000,3.592610e+05,3.594710e+05,359471.000000,0.0,0.0,...,2051.000000,0.0,303030.000000,3.314620e+05,208057.000000,344132.000000,276409.000000,3.313540e+05,0.0,46125.000000
mean,1.226082e+06,1.090707e+09,1.188227e+06,34.659295,-118.578239,1.907181e+03,1.139268e+06,36.297106,NaN,NaN,...,102.663194,NaN,1.364188,3.794994e+04,2.063675,1.859568,233.287792,3.189625e+05,NaN,221.929675
std,6.927357e+06,2.633906e+07,6.059275e+06,1.708719,2.969746,2.841294e+04,1.352650e+06,52.555171,NaN,NaN,...,774.274805,NaN,0.481203,2.128108e+06,7.612163,3.824284,1860.674952,1.562544e+07,NaN,2590.406598
min,0.000000e+00,4.216785e+08,0.000000e+00,-117.472493,-177.646696,0.000000e+00,5.250000e+02,-288.000000,NaN,NaN,...,0.000000,NaN,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,NaN,0.000000
25%,5.880000e+05,1.072798e+09,5.759030e+05,33.739021,-118.896600,1.246000e+03,5.790000e+05,8.000000,NaN,NaN,...,0.000000,NaN,1.000000,5.000000e+03,1.000000,2.000000,0.000000,5.227000e+03,NaN,2.000000
50%,8.290000e+05,1.089387e+09,8.250000e+05,34.048501,-118.019905,1.640000e+03,8.190000e+05,18.000000,NaN,NaN,...,0.000000,NaN,1.000000,7.018000e+03,2.000000,2.000000,94.360000,7.232000e+03,NaN,2.500000
75%,1.299000e+06,1.111937e+09,1.300000e+06,34.564502,-117.272241,2.214000e+03,1.295000e+06,47.000000,NaN,NaN,...,0.000000,NaN,2.000000,1.089000e+04,3.000000,2.000000,365.000000,1.176100e+04,NaN,2.500000
max,1.390000e+09,1.150042e+09,9.895000e+08,56.130366,329.000000,1.702132e+07,1.375000e+08,12430.000000,NaN,NaN,...,14531.000000,NaN,2.000000,9.187423e+08,3333.000000,600.000000,750000.000000,2.208318e+09,NaN,100000.000000

In [9]:
# Look at dataframe dimensions
sold_df.shape

(359471, 84)

In [10]:
# Check column data types
sold_df.info()

<class 'pandas.DataFrame'>
Index: 359471 entries, 0 to 532593
Data columns (total 84 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   BuyerAgentAOR                 313292 non-null  str
 1   ListAgentAOR                  313292 non-null  str
 2   Flooring                      230943 non-null  str
 3   ViewYN                        328615 non-null  object
 4   WaterfrontYN                  215 non-null     object
 5   BasementYN                    7085 non-null    object
 6   PoolPrivateYN                 327512 non-null  object
 7   OriginalListPrice             358844 non-null  float64
 8   ListingKey                    359471 non-null  int64
 9   ListAgentEmail                358536 non-null  str
 10  CloseDate                     359471 non-null  str
 11  ClosePrice                    359469 non-null  float64
 12  ListAgentFirstName            356661 non-null  str
 13  ListAgentLastName             359436 non-null  str
 14  Latitude                      343863 non-null  float64
 15  Longitude                     343863 non-null  float64
 16  UnparsedAddress               359147 non-null  str
 17  PropertyType                  359471 non-null  str
 18  LivingArea                    359261 non-null  float64
 19  ListPrice                     359471 non-null  float64
 20  DaysOnMarket                  359471 non-null  int64
 21  ListOfficeName                359471 non-null  str
 22  BuyerOfficeName               353381 non-null  str
 23  CoListOfficeName              85094 non-null   str
 24  ListAgentFullName             359412 non-null  str
 25  CoListAgentFirstName          82040 non-null   str
 26  CoListAgentLastName           82244 non-null   str
 27  BuyerAgentMlsId               359044 non-null  str
 28  BuyerAgentFirstName           357685 non-null  str
 29  BuyerAgentLastName            359334 non-null  str
 30  FireplacesTotal               0 non-null       float64
 31  AssociationFeeFrequency       149007 non-null  str
 32  AboveGradeFinishedArea        0 non-null       float64
 33  ListingKeyNumeric             359471 non-null  int64
 34  MLSAreaMajor                  311227 non-null  str
 35  TaxAnnualAmount               0 non-null       float64
 36  CountyOrParish                359471 non-null  str
 37  MlsStatus                     359471 non-null  str
 38  ElementarySchool              48432 non-null   str
 39  AttachedGarageYN              304793 non-null  object
 40  ParkingTotal                  359045 non-null  float64
 41  BuilderName                   17589 non-null   str
 42  PropertySubType               358776 non-null  str
 43  LotSizeAcres                  331018 non-null  float64
 44  SubdivisionName               133078 non-null  str
 45  BuyerOfficeAOR                342141 non-null  str
 46  YearBuilt                     359145 non-null  float64
 47  StreetNumberNumeric           359068 non-null  float64
 48  ListingId                     359471 non-null  str
 49  BathroomsTotalInteger         359404 non-null  float64
 50  City                          359167 non-null  str
 51  TaxYear                       0 non-null       float64
 52  BuildingAreaTotal             24993 non-null   float64
 53  BedroomsTotal                 359462 non-null  float64
 54  ContractStatusChangeDate      358882 non-null  str
 55  ElementarySchoolDistrict      0 non-null       float64
 56  CoBuyerAgentFirstName         32403 non-null   str
 57  PurchaseContractDate          359278 non-null  str
 58  ListingContractDate           359470 non-null  str
 59  BelowGradeFinishedArea        2051 non-null    float64
 60  BusinessType                  0 non-null       str
 61  StateOrProvince               359471 non-null  str
 62  CoveredSpaces                 0 non-null       float64
 63  MiddleOrJuniorSchool          48769 non-null   str
 64  FireplaceYN                   359192 non-null  object
 65  Stories                       303030 non-null  float64
 66  HighSchool                    63159 non-null   str
 67  Levels                        323762 non-null  str
 68  LotSizeDimensions             17426 non-null   str
 69  LotSizeArea                   331462 non-null  float64
 70  MainLevelBedrooms             208057 non-null  float64
 71  NewConstructionYN             332965 non-null  object
 72  GarageSpaces                  344132 non-null  float64
 73  HighSchoolDistrict            261456 non-null  str
 74  PostalCode                    359469 non-null  object
 75  AssociationFee                276409 non-null  float64
 76  LotSizeSquareFeet             331354 non-null  float64
 77  MiddleOrJuniorSchoolDistrict  0 non-null       float64
 78  OriginatingSystemName         11203 non-null   str
 79  OriginatingSystemSubName      11203 non-null   str
 80  BuyerAgencyCompensationType   46136 non-null   str
 81  BuyerAgencyCompensation       46125 non-null   float64
 82  latfilled                     63884 non-null   object
 83  lonfilled                     63884 non-null   object
dtypes: float64(28), int64(3), object(10), str(43)
memory usage: 233.1+ MB

In [11]:
# Look at missing values
sold_df.isnull().sum()

BuyerAgentAOR                   46179
ListAgentAOR                    46179
Flooring                       128528
ViewYN                          30856
WaterfrontYN                   359256
                                ...
OriginatingSystemSubName       348268
BuyerAgencyCompensationType    313335
BuyerAgencyCompensation        313346
latfilled                      295587
lonfilled                      295587
Length: 84, dtype: int64

In [12]:
# Check for rows where a house is sold but but doesn't have a close price
missing_close_price = sold_df[sold_df['ClosePrice'].isnull()]
print(f"Number of records that have no close price: {len(missing_close_price)}")

Number of records that have no close price: 2

## Dataset Structuring and Validation

In [13]:
# Inspect structure
sold_df.columns

Index(['BuyerAgentAOR', 'ListAgentAOR', 'Flooring', 'ViewYN', 'WaterfrontYN',
       'BasementYN', 'PoolPrivateYN', 'OriginalListPrice', 'ListingKey',
       'ListAgentEmail', 'CloseDate', 'ClosePrice', 'ListAgentFirstName',
       'ListAgentLastName', 'Latitude', 'Longitude', 'UnparsedAddress',
       'PropertyType', 'LivingArea', 'ListPrice', 'DaysOnMarket',
       'ListOfficeName', 'BuyerOfficeName', 'CoListOfficeName',
       'ListAgentFullName', 'CoListAgentFirstName', 'CoListAgentLastName',
       'BuyerAgentMlsId', 'BuyerAgentFirstName', 'BuyerAgentLastName',
       'FireplacesTotal', 'AssociationFeeFrequency', 'AboveGradeFinishedArea',
       'ListingKeyNumeric', 'MLSAreaMajor', 'TaxAnnualAmount',
       'CountyOrParish', 'MlsStatus', 'ElementarySchool', 'AttachedGarageYN',
       'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'StreetNumberNumeric',
       'ListingId', 'BathroomsTotalInteger', 'City', 'TaxYear',
       'BuildingAreaTotal', 'BedroomsTotal', 'ContractStatusChangeDate',
       'ElementarySchoolDistrict', 'CoBuyerAgentFirstName',
       'PurchaseContractDate', 'ListingContractDate', 'BelowGradeFinishedArea',
       'BusinessType', 'StateOrProvince', 'CoveredSpaces',
       'MiddleOrJuniorSchool', 'FireplaceYN', 'Stories', 'HighSchool',
       'Levels', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'AssociationFee', 'LotSizeSquareFeet', 'MiddleOrJuniorSchoolDistrict',
       'OriginatingSystemName', 'OriginatingSystemSubName',
       'BuyerAgencyCompensationType', 'BuyerAgencyCompensation', 'latfilled',
       'lonfilled'],
      dtype='str')

In [14]:
sold_df.head()

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,...,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,OriginatingSystemName,OriginatingSystemSubName,BuyerAgencyCompensationType,BuyerAgencyCompensation,latfilled,lonfilled
0,Mlslistings,Mlslistings,"Carpet,Tile,Wood",True,NaN,NaN,False,499000.0,551985747,jwachter@cbnorcal.com,...,94401,6472.0,NaN,NaN,CRMLS,CRMLS_MLSL,NaN,NaN,NaN,NaN
5,SanDiego,SanDiego,NaN,False,NaN,NaN,False,759900.0,522107581,mdarwich12@gmail.com,...,91950,NaN,NaN,NaN,CRMLS,CRMLS_SAND,NaN,NaN,NaN,NaN
9,SanDiego,SanDiego,NaN,False,NaN,NaN,False,739900.0,510919001,mdarwich12@gmail.com,...,91950,NaN,NaN,NaN,CRMLS,CRMLS_SAND,NaN,NaN,NaN,NaN
28,Mlslistings,Mlslistings,NaN,False,NaN,NaN,NaN,NaN,1079166779,davidmartz@compass.com,...,92262,NaN,13504.0,NaN,CRMLS,CRMLS_MLSL,NaN,NaN,NaN,NaN
29,Southland,Southland,NaN,False,NaN,NaN,False,1890500.0,1075037759,karen.klein@theagencyre.com,...,91356,0.0,17873.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN

In [15]:
# Check property categories
sold_df['PropertyType'].unique()

<StringArray>
['Residential']
Length: 1, dtype: str

In [16]:
# Validate completeness
sold_df.isnull().sum()

BuyerAgentAOR                   46179
ListAgentAOR                    46179
Flooring                       128528
ViewYN                          30856
WaterfrontYN                   359256
                                ...
OriginatingSystemSubName       348268
BuyerAgencyCompensationType    313335
BuyerAgencyCompensation        313346
latfilled                      295587
lonfilled                      295587
Length: 84, dtype: int64

## Data Cleaning and Preparation

In [17]:
# Convert data fields to datetime format
sold_df['CloseDate'] = pd.to_datetime(sold_df['CloseDate'])
sold_df['ListingContractDate'] = pd.to_datetime(sold_df['ListingContractDate'])

In [18]:
# Check for duplicates
sold_df[sold_df.duplicated(subset='ListingKey')]
sold_df = sold_df.drop_duplicates(subset=['ListingKey'], keep='last') # Keep the most recent property with the listing key

In [19]:
# Drop rows if missing critical value
must_columns = ['ListingKey', 'ClosePrice', 'CloseDate', 'City']
sold_df = sold_df.dropna(subset=must_columns)

In [20]:
# Removing missing columns with too many missing values
threshold = len(sold_df) * 0.70
sold_df = sold_df.dropna(thresh=threshold, axis = 1)
# print(f'Columns remaining: {len(sold_df.columns)}')

In [21]:
# Fill in missing counts with '0'
zero_fill_cols = ['GarageSpaces', 'ParkingTotal', 'FireplacesTotal']

for col in zero_fill_cols:
    if col in sold_df.columns:
        sold_df[col] = sold_df[col].fillna(0)

# Fill in missing Yes/No features with 'No'
fill_no_cols = ['PoolPrivateYN', 'ViewYN', 'CoolingYN', 'HeatingYN']
for col in fill_no_cols:
    if col in sold_df.columns:
        sold_df[col] = sold_df[col].fillna(False)

# Fill in missing categorical data with "Unknown"
cat_fill_cols = ['ArchitectureStyle', 'Heating', 'Cooling', 'WaterSource']
for col in cat_fill_cols:
    if col in sold_df.columns:
        sold_df[col] = sold_df[col].fillna('Unknown')

# Fill in missing numerical values
num_fill_cols = ['LotSizeArea', 'YearBuilt']
for col in num_fill_cols:
    if col in sold_df.columns:
        col_median = sold_df[col].median()
        sold_df[col] = sold_df[col].fillna(col_median)

In [22]:
# Drop missing Living Area
sold_df = sold_df.dropna(subset='LivingArea')
# Filter out where Living Area is less than 0
sold_df = sold_df[sold_df['LivingArea'] > 0]

## Feature Engineering and Market Metrics

In [23]:
sold_df['PriceRatio'] = sold_df['ClosePrice'] / sold_df['OriginalListPrice']
sold_df['PricePerSqFt'] = sold_df['ClosePrice'] / sold_df['LivingArea']
sold_df['Year'] = sold_df['CloseDate'].dt.year
sold_df['Month'] = sold_df['CloseDate'].dt.month
sold_df['YrMo'] = sold_df['CloseDate'].dt.to_period('M').astype(str)

## Outlier Detection and Data Quality

In [24]:
Q1 = sold_df['ClosePrice'].quantile(0.25)
Q3 = sold_df['ClosePrice'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1- 1.5 * IQR
upper = Q3 + 1.5 * IQR

sold_df = sold_df[(sold_df['ClosePrice'] >= lower) & (sold_df['ClosePrice'] <= upper)]

## Export to CSV for Tableau

In [25]:
sold_df.to_scv('CRMLSSold_Clean.csv', index=False)

AttributeError: 'DataFrame' object has no attribute 'to_scv'