# CRMLS Sold Data Analysis

In [146]:
import pandas as pd
import glob

## Combine the data

In [147]:
# Get all CRMLSSold files
sold_data = glob.glob('**/CRMLSSold*.csv',recursive=True)

df_list = []
for file in sold_data:
    df = pd.read_csv(file, encoding='ISO-8859-1',low_memory=True)
    df_list.append(df)
sold_df = pd.concat(df_list, ignore_index=True)

C:\Users\caden\AppData\Local\Temp\ipykernel_14704\2329637334.py:6: DtypeWarning: Columns (0: WaterfrontYN, 1: ElementarySchool, 2: BuilderName, 3: CoBuyerAgentFirstName, 4: PostalCode) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, encoding='ISO-8859-1',low_memory=True)
C:\Users\caden\AppData\Local\Temp\ipykernel_14704\2329637334.py:6: DtypeWarning: Columns (0: WaterfrontYN) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, encoding='ISO-8859-1',low_memory=True)

## Data Exploration

In [148]:
sold_df.head()

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,CloseDate,...,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,OriginatingSystemName,OriginatingSystemSubName,ListAgentEmail,BuyerAgencyCompensationType,BuyerAgencyCompensation,latfilled,lonfilled
0,HighDesert,HighDesert,NaN,False,NaN,NaN,False,1850000.0,1156290692,2026-02-26,...,0.0,29698.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN,NaN
1,ContraCosta,BayEast,NaN,NaN,NaN,NaN,NaN,1580000.0,1155696412,2026-02-19,...,0.0,18682.0,NaN,CRMLS,CRMLS_CCBE,NaN,NaN,NaN,NaN,NaN
2,OrangeCounty,OrangeCounty,"Carpet,Tile",False,NaN,NaN,False,1100000.0,1155620121,2026-02-27,...,NaN,5000.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN,NaN
3,BeverlyHillsGreaterLa,BeverlyHillsGreaterLa,Wood,False,NaN,NaN,False,999000.0,1155350576,2026-02-27,...,NaN,12005.0,NaN,CRMLS,CRMLS_CL,NaN,NaN,NaN,NaN,NaN
4,SanDiego,SanDiego,NaN,NaN,NaN,NaN,NaN,1650000.0,1155221012,2026-02-14,...,0.0,6851.0,NaN,CRMLS,CRMLS_SAND,NaN,NaN,NaN,NaN,NaN

In [149]:
# Look at dataframe columns
sold_df.columns

Index(['BuyerAgentAOR', 'ListAgentAOR', 'Flooring', 'ViewYN', 'WaterfrontYN',
       'BasementYN', 'PoolPrivateYN', 'OriginalListPrice', 'ListingKey',
       'CloseDate', 'ClosePrice', 'ListAgentFirstName', 'ListAgentLastName',
       'Latitude', 'Longitude', 'UnparsedAddress', 'PropertyType',
       'LivingArea', 'ListPrice', 'DaysOnMarket', 'ListOfficeName',
       'BuyerOfficeName', 'CoListOfficeName', 'ListAgentFullName',
       'CoListAgentFirstName', 'CoListAgentLastName', 'BuyerAgentMlsId',
       'BuyerAgentFirstName', 'BuyerAgentLastName', 'FireplacesTotal',
       'AssociationFeeFrequency', 'AboveGradeFinishedArea',
       'ListingKeyNumeric', 'MLSAreaMajor', 'TaxAnnualAmount',
       'CountyOrParish', 'MlsStatus', 'ElementarySchool', 'AttachedGarageYN',
       'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'StreetNumberNumeric',
       'ListingId', 'BathroomsTotalInteger', 'City', 'TaxYear',
       'BuildingAreaTotal', 'BedroomsTotal', 'ContractStatusChangeDate',
       'ElementarySchoolDistrict', 'CoBuyerAgentFirstName',
       'PurchaseContractDate', 'ListingContractDate', 'BelowGradeFinishedArea',
       'BusinessType', 'StateOrProvince', 'CoveredSpaces',
       'MiddleOrJuniorSchool', 'FireplaceYN', 'Stories', 'HighSchool',
       'Levels', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'AssociationFee', 'LotSizeSquareFeet', 'MiddleOrJuniorSchoolDistrict',
       'OriginatingSystemName', 'OriginatingSystemSubName', 'ListAgentEmail',
       'BuyerAgencyCompensationType', 'BuyerAgencyCompensation', 'latfilled',
       'lonfilled'],
      dtype='str')

In [150]:
# Look at statistics of numerical columns
sold_df.describe()

,OriginalListPrice,ListingKey,ClosePrice,Latitude,Longitude,LivingArea,ListPrice,DaysOnMarket,FireplacesTotal,AboveGradeFinishedArea,...,BelowGradeFinishedArea,CoveredSpaces,Stories,LotSizeArea,MainLevelBedrooms,GarageSpaces,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,BuyerAgencyCompensation
count,5.500850e+05,5.516760e+05,5.516690e+05,532901.000000,533059.000000,5.127630e+05,5.508280e+05,551676.000000,0.0,0.0,...,2418.000000,0.0,440485.000000,5.008350e+05,292084.000000,481369.000000,380321.000000,5.004080e+05,0.0,67780.000000
mean,9.112206e+05,1.092393e+09,8.769356e+05,34.531676,-118.456779,3.617630e+03,8.422770e+05,42.699949,NaN,NaN,...,107.725066,NaN,1.364968,4.809232e+04,1.933998,1.766864,185.111977,4.623950e+05,NaN,194.406143
std,5.929910e+06,3.136981e+07,5.289129e+06,1.616600,3.101174,1.269768e+06,1.274598e+06,69.574023,NaN,NaN,...,813.480427,NaN,0.481422,2.238722e+06,6.467026,3.893122,1687.894358,2.057766e+07,NaN,2152.716451
min,0.000000e+00,4.214490e+08,0.000000e+00,-117.472493,-177.646696,0.000000e+00,0.000000e+00,-288.000000,NaN,NaN,...,0.000000,NaN,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,NaN,0.000000
25%,7.500000e+04,1.073169e+09,6.000000e+04,33.740285,-118.541779,1.184000e+03,7.000000e+04,9.000000,NaN,NaN,...,0.000000,NaN,1.000000,4.942000e+03,1.000000,1.000000,0.000000,5.176750e+03,NaN,2.000000
50%,6.450000e+05,1.090258e+09,6.300000e+05,34.038899,-118.044642,1.580000e+03,6.344585e+05,22.000000,NaN,NaN,...,0.000000,NaN,1.000000,7.020000e+03,2.000000,2.000000,0.000000,7.280000e+03,NaN,2.500000
75%,1.095000e+06,1.112984e+09,1.075000e+06,34.319018,-117.330878,2.150000e+03,1.065000e+06,53.000000,NaN,NaN,...,0.000000,NaN,2.000000,1.141700e+04,3.000000,2.000000,295.000000,1.281500e+04,NaN,2.500000
max,1.390000e+09,1.156291e+09,9.895000e+08,157.000000,329.000000,9.090909e+08,1.375000e+08,12430.000000,NaN,NaN,...,17424.000000,NaN,2.000000,9.187423e+08,3333.000000,600.000000,750000.000000,5.193920e+09,NaN,100000.000000

In [151]:
# Look at dataframe dimensions
sold_df.shape

(551676, 84)

In [152]:
# Check column data types
sold_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 551676 entries, 0 to 551675
Data columns (total 84 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   BuyerAgentAOR                 482130 non-null  str
 1   ListAgentAOR                  483644 non-null  str
 2   Flooring                      324570 non-null  str
 3   ViewYN                        496155 non-null  object
 4   WaterfrontYN                  301 non-null     object
 5   BasementYN                    9155 non-null    object
 6   PoolPrivateYN                 481752 non-null  object
 7   OriginalListPrice             550085 non-null  float64
 8   ListingKey                    551676 non-null  int64
 9   CloseDate                     551676 non-null  str
 10  ClosePrice                    551669 non-null  float64
 11  ListAgentFirstName            548394 non-null  str
 12  ListAgentLastName             551619 non-null  str
 13  Latitude                      532901 non-null  float64
 14  Longitude                     533059 non-null  float64
 15  UnparsedAddress               550834 non-null  str
 16  PropertyType                  551676 non-null  str
 17  LivingArea                    512763 non-null  float64
 18  ListPrice                     550828 non-null  float64
 19  DaysOnMarket                  551676 non-null  int64
 20  ListOfficeName                551676 non-null  str
 21  BuyerOfficeName               544680 non-null  str
 22  CoListOfficeName              118590 non-null  str
 23  ListAgentFullName             551547 non-null  str
 24  CoListAgentFirstName          113912 non-null  str
 25  CoListAgentLastName           114142 non-null  str
 26  BuyerAgentMlsId               550042 non-null  str
 27  BuyerAgentFirstName           549194 non-null  str
 28  BuyerAgentLastName            551374 non-null  str
 29  FireplacesTotal               0 non-null       float64
 30  AssociationFeeFrequency       163113 non-null  str
 31  AboveGradeFinishedArea        0 non-null       float64
 32  ListingKeyNumeric             551676 non-null  int64
 33  MLSAreaMajor                  490715 non-null  str
 34  TaxAnnualAmount               2377 non-null    float64
 35  CountyOrParish                551676 non-null  str
 36  MlsStatus                     551676 non-null  str
 37  ElementarySchool              61642 non-null   str
 38  AttachedGarageYN              399341 non-null  object
 39  ParkingTotal                  534208 non-null  float64
 40  BuilderName                   21135 non-null   str
 41  PropertySubType               509326 non-null  str
 42  LotSizeAcres                  499094 non-null  float64
 43  SubdivisionName               194296 non-null  str
 44  BuyerOfficeAOR                529596 non-null  str
 45  YearBuilt                     528529 non-null  float64
 46  StreetNumberNumeric           550303 non-null  float64
 47  ListingId                     551676 non-null  str
 48  BathroomsTotalInteger         526089 non-null  float64
 49  City                          551237 non-null  str
 50  TaxYear                       343 non-null     float64
 51  BuildingAreaTotal             71159 non-null   float64
 52  BedroomsTotal                 514908 non-null  float64
 53  ContractStatusChangeDate      550964 non-null  str
 54  ElementarySchoolDistrict      0 non-null       float64
 55  CoBuyerAgentFirstName         44750 non-null   str
 56  PurchaseContractDate          540741 non-null  str
 57  ListingContractDate           551599 non-null  str
 58  BelowGradeFinishedArea        2418 non-null    float64
 59  BusinessType                  1521 non-null    str
 60  StateOrProvince               551676 non-null  str
 61  CoveredSpaces                 0 non-null       float64
 62  MiddleOrJuniorSchool          62065 non-null   str
 63  FireplaceYN                   503431 non-null  object
 64  Stories                       440485 non-null  float64
 65  HighSchool                    80771 non-null   str
 66  Levels                        475011 non-null  str
 67  LotSizeDimensions             28840 non-null   str
 68  LotSizeArea                   500835 non-null  float64
 69  MainLevelBedrooms             292084 non-null  float64
 70  NewConstructionYN             486230 non-null  object
 71  GarageSpaces                  481369 non-null  float64
 72  HighSchoolDistrict            368108 non-null  str
 73  PostalCode                    551522 non-null  object
 74  AssociationFee                380321 non-null  float64
 75  LotSizeSquareFeet             500408 non-null  float64
 76  MiddleOrJuniorSchoolDistrict  0 non-null       float64
 77  OriginatingSystemName         37057 non-null   str
 78  OriginatingSystemSubName      37057 non-null   str
 79  ListAgentEmail                531268 non-null  str
 80  BuyerAgencyCompensationType   67747 non-null   str
 81  BuyerAgencyCompensation       67780 non-null   float64
 82  latfilled                     95793 non-null   object
 83  lonfilled                     95793 non-null   object
dtypes: float64(28), int64(3), object(10), str(43)
memory usage: 353.6+ MB

In [153]:
# Look at missing values
sold_df.isnull().sum()

BuyerAgentAOR                   69546
ListAgentAOR                    68032
Flooring                       227106
ViewYN                          55521
WaterfrontYN                   551375
                                ...
ListAgentEmail                  20408
BuyerAgencyCompensationType    483929
BuyerAgencyCompensation        483896
latfilled                      455883
lonfilled                      455883
Length: 84, dtype: int64

In [154]:
# Check for rows where a house is sold but but doesn't have a close price
missing_close_price = sold_df[sold_df['ClosePrice'].isnull()]
print(f"Number of records that have no close price: {len(missing_close_price)}")

Number of records that have no close price: 7

## Dataset Structuring and Validation

In [155]:
# Inspect structure
sold_df.columns

Index(['BuyerAgentAOR', 'ListAgentAOR', 'Flooring', 'ViewYN', 'WaterfrontYN',
       'BasementYN', 'PoolPrivateYN', 'OriginalListPrice', 'ListingKey',
       'CloseDate', 'ClosePrice', 'ListAgentFirstName', 'ListAgentLastName',
       'Latitude', 'Longitude', 'UnparsedAddress', 'PropertyType',
       'LivingArea', 'ListPrice', 'DaysOnMarket', 'ListOfficeName',
       'BuyerOfficeName', 'CoListOfficeName', 'ListAgentFullName',
       'CoListAgentFirstName', 'CoListAgentLastName', 'BuyerAgentMlsId',
       'BuyerAgentFirstName', 'BuyerAgentLastName', 'FireplacesTotal',
       'AssociationFeeFrequency', 'AboveGradeFinishedArea',
       'ListingKeyNumeric', 'MLSAreaMajor', 'TaxAnnualAmount',
       'CountyOrParish', 'MlsStatus', 'ElementarySchool', 'AttachedGarageYN',
       'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'StreetNumberNumeric',
       'ListingId', 'BathroomsTotalInteger', 'City', 'TaxYear',
       'BuildingAreaTotal', 'BedroomsTotal', 'ContractStatusChangeDate',
       'ElementarySchoolDistrict', 'CoBuyerAgentFirstName',
       'PurchaseContractDate', 'ListingContractDate', 'BelowGradeFinishedArea',
       'BusinessType', 'StateOrProvince', 'CoveredSpaces',
       'MiddleOrJuniorSchool', 'FireplaceYN', 'Stories', 'HighSchool',
       'Levels', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'AssociationFee', 'LotSizeSquareFeet', 'MiddleOrJuniorSchoolDistrict',
       'OriginatingSystemName', 'OriginatingSystemSubName', 'ListAgentEmail',
       'BuyerAgencyCompensationType', 'BuyerAgencyCompensation', 'latfilled',
       'lonfilled'],
      dtype='str')

In [156]:
sold_df.head()

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,CloseDate,...,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,OriginatingSystemName,OriginatingSystemSubName,ListAgentEmail,BuyerAgencyCompensationType,BuyerAgencyCompensation,latfilled,lonfilled
0,HighDesert,HighDesert,NaN,False,NaN,NaN,False,1850000.0,1156290692,2026-02-26,...,0.0,29698.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN,NaN
1,ContraCosta,BayEast,NaN,NaN,NaN,NaN,NaN,1580000.0,1155696412,2026-02-19,...,0.0,18682.0,NaN,CRMLS,CRMLS_CCBE,NaN,NaN,NaN,NaN,NaN
2,OrangeCounty,OrangeCounty,"Carpet,Tile",False,NaN,NaN,False,1100000.0,1155620121,2026-02-27,...,NaN,5000.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN,NaN
3,BeverlyHillsGreaterLa,BeverlyHillsGreaterLa,Wood,False,NaN,NaN,False,999000.0,1155350576,2026-02-27,...,NaN,12005.0,NaN,CRMLS,CRMLS_CL,NaN,NaN,NaN,NaN,NaN
4,SanDiego,SanDiego,NaN,NaN,NaN,NaN,NaN,1650000.0,1155221012,2026-02-14,...,0.0,6851.0,NaN,CRMLS,CRMLS_SAND,NaN,NaN,NaN,NaN,NaN

In [157]:
# Check property categories
sold_df['PropertyType'].unique()

<StringArray>
[  'ResidentialIncome',         'Residential',      'CommercialSale',
                'Land',    'ResidentialLease',  'ManufacturedInPark',
     'CommercialLease', 'BusinessOpportunity']
Length: 8, dtype: str

In [158]:
# Filter to residential
sold_df = sold_df[sold_df['PropertyType'] == "Residential"]

In [159]:
# Validate completeness
sold_df.isnull().sum()

BuyerAgentAOR                   47440
ListAgentAOR                    46181
Flooring                       133133
ViewYN                          31872
WaterfrontYN                   371532
                                ...
ListAgentEmail                  13226
BuyerAgencyCompensationType    325626
BuyerAgencyCompensation        325637
latfilled                      307878
lonfilled                      307878
Length: 84, dtype: int64

## Data Cleaning and Preparation

In [160]:
# Convert data fields to datetime format
sold_df['CloseDate'] = pd.to_datetime(sold_df['CloseDate'])
sold_df['ListingContractDate'] = pd.to_datetime(sold_df['ListingContractDate'])

In [161]:
# Check for duplicates
sold_df[sold_df.duplicated(subset='ListingKey')]
sold_df = sold_df.drop_duplicates(subset=['ListingKey'], keep='last') # Keep the most recent property with the listing key

In [162]:
# Removing missing columns with too many missing values
threshold = len(sold_df) * 0.70
sold_df = sold_df.dropna(thresh=threshold, axis = 1)
# print(f'Columns remaining: {len(sold_df.columns)}')

In [163]:
# Drop rows if missing critical value
must_columns = ['ListingKey', 'ClosePrice', 'CloseDate', 'City']
sold_df = sold_df.dropna(subset=must_columns)

In [164]:
# Fill in missing counts with '0'
zero_fill_cols = ['GarageSpaces', 'ParkingTotal', 'FireplacesTotal']

for col in zero_fill_cols:
    if col in sold_df.columns:
        sold_df[col] = sold_df[col].fillna(0)

# Fill in missing Yes/No features with 'No'
no_fill_cols = ['PoolPrivateYN', 'ViewYN', 'CoolingYN', 'HeatingYN']
for col in no_fill_cols:
    if col in sold_df.columns:
        sold_df[col] = sold_df[col].fillna(False)

# Fill in missing categorical data with "Unknown"
cat_fill_cols = ['ArchitectureStyle', 'Heating', 'Cooling', 'WaterSource']
for col in cat_fill_cols:
    if col in sold_df.columns:
        sold_df[col] = sold_df[col].fillna('Unknown')

# Fill in missing numerical values
num_fill_cols = ['LotSizeArea', 'YearBuilt']
for col in num_fill_cols:
    if col in sold_df.columns:
        col_median = sold_df[col].median()
        sold_df[col] = sold_df[col].fillna(col_median)

In [165]:
# Drop missing Living Area
sold_df = sold_df.dropna(subset='LivingArea')
# Filter out where Living Area is less than 0
sold_df = sold_df[sold_df['LivingArea'] > 0]