# CRMLS Sold Data Analysis

In [1]:
import pandas as pd
import glob

## Combine the data

In [2]:
# Get all CRMLSSold files
sold_data = glob.glob('**/CRMLSSold*.csv',recursive=True)

df_list = []
for file in sold_data:
    df = pd.read_csv(file, encoding='ISO-8859-1',low_memory=True)
    df_list.append(df)
sold_df = pd.concat(df_list, ignore_index=True)

C:\Users\caden\AppData\Local\Temp\ipykernel_20984\2329637334.py:6: DtypeWarning: Columns (0: WaterfrontYN, 1: ElementarySchool, 2: BuilderName, 3: CoBuyerAgentFirstName, 4: PostalCode) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, encoding='ISO-8859-1',low_memory=True)
C:\Users\caden\AppData\Local\Temp\ipykernel_20984\2329637334.py:6: DtypeWarning: Columns (0: WaterfrontYN) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, encoding='ISO-8859-1',low_memory=True)

## Exploratory Data Analysis

In [3]:
sold_df.head()

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,CloseDate,...,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,OriginatingSystemName,OriginatingSystemSubName,ListAgentEmail,BuyerAgencyCompensationType,BuyerAgencyCompensation,latfilled,lonfilled
0,HighDesert,HighDesert,NaN,False,NaN,NaN,False,1850000.0,1156290692,2026-02-26,...,0.0,29698.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN,NaN
1,ContraCosta,BayEast,NaN,NaN,NaN,NaN,NaN,1580000.0,1155696412,2026-02-19,...,0.0,18682.0,NaN,CRMLS,CRMLS_CCBE,NaN,NaN,NaN,NaN,NaN
2,OrangeCounty,OrangeCounty,"Carpet,Tile",False,NaN,NaN,False,1100000.0,1155620121,2026-02-27,...,NaN,5000.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN,NaN
3,BeverlyHillsGreaterLa,BeverlyHillsGreaterLa,Wood,False,NaN,NaN,False,999000.0,1155350576,2026-02-27,...,NaN,12005.0,NaN,CRMLS,CRMLS_CL,NaN,NaN,NaN,NaN,NaN
4,SanDiego,SanDiego,NaN,NaN,NaN,NaN,NaN,1650000.0,1155221012,2026-02-14,...,0.0,6851.0,NaN,CRMLS,CRMLS_SAND,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Look at dataframe columns
sold_df.columns

Index(['BuyerAgentAOR', 'ListAgentAOR', 'Flooring', 'ViewYN', 'WaterfrontYN',
       'BasementYN', 'PoolPrivateYN', 'OriginalListPrice', 'ListingKey',
       'CloseDate', 'ClosePrice', 'ListAgentFirstName', 'ListAgentLastName',
       'Latitude', 'Longitude', 'UnparsedAddress', 'PropertyType',
       'LivingArea', 'ListPrice', 'DaysOnMarket', 'ListOfficeName',
       'BuyerOfficeName', 'CoListOfficeName', 'ListAgentFullName',
       'CoListAgentFirstName', 'CoListAgentLastName', 'BuyerAgentMlsId',
       'BuyerAgentFirstName', 'BuyerAgentLastName', 'FireplacesTotal',
       'AssociationFeeFrequency', 'AboveGradeFinishedArea',
       'ListingKeyNumeric', 'MLSAreaMajor', 'TaxAnnualAmount',
       'CountyOrParish', 'MlsStatus', 'ElementarySchool', 'AttachedGarageYN',
       'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'StreetNumberNumeric',
       'ListingId', 'BathroomsTotalInteger', 'City', 'TaxYear',
       'BuildingAreaTotal', 'BedroomsTotal', 'ContractStatusChangeDate',
       'ElementarySchoolDistrict', 'CoBuyerAgentFirstName',
       'PurchaseContractDate', 'ListingContractDate', 'BelowGradeFinishedArea',
       'BusinessType', 'StateOrProvince', 'CoveredSpaces',
       'MiddleOrJuniorSchool', 'FireplaceYN', 'Stories', 'HighSchool',
       'Levels', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'AssociationFee', 'LotSizeSquareFeet', 'MiddleOrJuniorSchoolDistrict',
       'OriginatingSystemName', 'OriginatingSystemSubName', 'ListAgentEmail',
       'BuyerAgencyCompensationType', 'BuyerAgencyCompensation', 'latfilled',
       'lonfilled'],
      dtype='str')

In [7]:
# Look at statistics of numerical columns
df.describe()

,OriginalListPrice,ListingKey,ClosePrice,Latitude,Longitude,LivingArea,ListPrice,DaysOnMarket,FireplacesTotal,AboveGradeFinishedArea,...,ElementarySchoolDistrict,BelowGradeFinishedArea,CoveredSpaces,Stories,LotSizeArea,MainLevelBedrooms,GarageSpaces,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict
count,2.047400e+04,2.053800e+04,2.053800e+04,20534.000000,20534.000000,18858.000000,2.050000e+04,20538.000000,0.0,0.0,...,0.0,104.000000,0.0,16719.000000,1.873200e+04,11189.000000,17811.000000,14673.000000,1.871400e+04,0.0
mean,1.011555e+06,1.136016e+09,8.939072e+05,34.512442,-118.408123,1824.244273,8.516679e+05,53.837423,NaN,NaN,...,NaN,67.634615,NaN,1.358933,4.073321e+04,1.961391,1.763685,182.515696,6.153905e+05,NaN
std,8.650949e+06,1.833745e+07,6.138006e+06,1.647828,3.435537,1251.533383,1.267172e+06,76.564351,NaN,NaN,...,NaN,318.452358,NaN,0.479702,5.277870e+05,1.478463,3.939541,428.817655,1.895876e+07,NaN
min,0.000000e+00,4.252871e+08,1.400000e+00,0.000000,-156.450301,0.000000,1.250000e+00,-4.000000,NaN,NaN,...,NaN,0.000000,NaN,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,NaN
25%,1.550000e+05,1.131250e+09,1.352500e+05,33.742923,-118.528620,1180.000000,1.527500e+05,12.000000,NaN,NaN,...,NaN,0.000000,NaN,1.000000,4.800000e+03,1.000000,1.000000,0.000000,5.227000e+03,NaN
50%,6.500000e+05,1.139705e+09,6.349900e+05,34.042987,-118.039407,1581.500000,6.432075e+05,32.000000,NaN,NaN,...,NaN,0.000000,NaN,1.000000,6.995000e+03,2.000000,2.000000,0.000000,7.348000e+03,NaN
75%,1.095000e+06,1.145816e+09,1.050000e+06,34.294849,-117.297550,2163.000000,1.050000e+06,69.000000,NaN,NaN,...,NaN,0.000000,NaN,2.000000,1.132500e+04,3.000000,2.000000,290.000000,1.334000e+04,NaN
max,6.990000e+08,1.150042e+09,7.650000e+08,43.784440,120.383521,61439.000000,4.995000e+07,2365.000000,NaN,NaN,...,NaN,2614.000000,NaN,2.000000,4.464900e+07,32.000000,500.000000,18518.000000,1.500250e+09,NaN

In [8]:
# Look at dataframe dimensions
sold_df.shape

(551676, 84)