# Week 1-2 Data Exploration and Python Exploration

## Reading in the datasets

In [20]:
# Import libraries
import pandas as pd

In [21]:
# Read in datasets
listings_df = pd.read_csv('CRMLSListing202602.csv', encoding='ISO-8859-1')
sold_df = pd.read_csv('CRMLSSold202602.csv', encoding='ISO-8859-1')

In [22]:
listings_df.head()

,OriginalListPrice,ListingKey,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,PropertyType,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1
0,1775000.0,1156313594,NaN,NaN,Diana,Trinh-Salzer,34.181456,-119.232985,4575 Gateshead Bay,Residential,...,NaN,NaN,2.0,NaN,93035,NaN,NaN,2800.0,NaN,4575 Gateshead Bay
1,2900000.0,1156305330,2026-03-12,2900000.0,Molly,Fleming,32.988714,-117.263012,618 Sonrisa St.,Residential,...,NaN,NaN,2.0,San Dieguito Union,92075,Compass,0.0,11200.0,NaN,618 Sonrisa St.
2,519000.0,1156298355,NaN,NaN,Hans,Hagenmayer,34.258190,-118.326305,8780 1/2 Wyngate Street,Residential,...,NaN,NaN,2.0,NaN,91040,NaN,681.0,299257.2,NaN,8780 1/2 Wyngate Street
3,4698000.0,1156294964,NaN,NaN,Robyn,Robinson,33.504678,-117.638115,31445 Juliana Farms Road,Residential,...,2.0,False,4.0,Capistrano Unified,92675,NaN,535.0,26702.0,NaN,31445 Juliana Farms Road
4,1100000.0,1156294960,2026-03-17,1100000.0,Hamid,Koochak,34.016973,-118.368336,5625 Aladdin Street,Residential,...,NaN,False,NaN,NaN,90008,Compass,320.0,13225.0,NaN,5625 Aladdin Street

In [23]:
sold_df.head()

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,CloseDate,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,OriginatingSystemName,OriginatingSystemSubName
0,HighDesert,HighDesert,NaN,False,NaN,NaN,False,1850000.0,1156290692,2026-02-26,...,NaN,False,20.0,NaN,92307,0.0,29698.0,NaN,CRMLS,CRMLS_CRM
1,ContraCosta,BayEast,NaN,NaN,NaN,NaN,NaN,1580000.0,1155696412,2026-02-19,...,NaN,NaN,NaN,NaN,95821,0.0,18682.0,NaN,CRMLS,CRMLS_CCBE
2,OrangeCounty,OrangeCounty,"Carpet,Tile",False,NaN,NaN,False,1100000.0,1155620121,2026-02-27,...,3.0,False,2.0,Irvine Unified,92604,NaN,5000.0,NaN,CRMLS,CRMLS_CRM
3,BeverlyHillsGreaterLa,BeverlyHillsGreaterLa,Wood,False,NaN,NaN,False,999000.0,1155350576,2026-02-27,...,NaN,False,NaN,NaN,91411,NaN,12005.0,NaN,CRMLS,CRMLS_CL
4,SanDiego,SanDiego,NaN,NaN,NaN,NaN,NaN,1650000.0,1155221012,2026-02-14,...,NaN,NaN,NaN,NaN,91910,0.0,6851.0,NaN,CRMLS,CRMLS_SAND

In [24]:
print(f'Listing columns: \n{listings_df.columns} \n Sold columns: \n{sold_df.columns}')

Listing columns:
Index(['OriginalListPrice', 'ListingKey', 'CloseDate', 'ClosePrice',
       'ListAgentFirstName', 'ListAgentLastName', 'Latitude', 'Longitude',
       'UnparsedAddress', 'PropertyType', 'LivingArea', 'ListPrice',
       'DaysOnMarket', 'ListOfficeName', 'BuyerOfficeName', 'CoListOfficeName',
       'ListAgentFullName', 'CoListAgentFirstName', 'CoListAgentLastName',
       'BuyerAgentMlsId', 'BuyerAgentFirstName', 'BuyerAgentLastName',
       'FireplacesTotal', 'AssociationFeeFrequency', 'AboveGradeFinishedArea',
       'ListingKeyNumeric', 'MLSAreaMajor', 'TaxAnnualAmount',
       'CountyOrParish', 'PropertyType.1', 'MlsStatus', 'ElementarySchool',
       'ListAgentFirstName.1', 'AttachedGarageYN', 'ParkingTotal',
       'BuilderName', 'PropertySubType', 'LotSizeAcres', 'SubdivisionName',
       'BuyerOfficeAOR', 'YearBuilt', 'DaysOnMarket.1', 'StreetNumberNumeric',
       'LivingArea.1', 'ListingId', 'BathroomsTotalInteger', 'City', 'TaxYear',
       'BuildingAreaTotal', 'BedroomsTotal', 'ContractStatusChangeDate',
       'Longitude.1', 'ElementarySchoolDistrict', 'CoBuyerAgentFirstName',
       'PurchaseContractDate', 'ListingContractDate', 'BelowGradeFinishedArea',
       'BusinessType', 'Latitude.1', 'ListPrice.1', 'StateOrProvince',
       'CoveredSpaces', 'MiddleOrJuniorSchool', 'FireplaceYN', 'Stories',
       'HighSchool', 'Levels', 'ListAgentLastName.1', 'CloseDate.1',
       'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'BuyerOfficeName.1', 'AssociationFee', 'LotSizeSquareFeet',
       'MiddleOrJuniorSchoolDistrict', 'UnparsedAddress.1'],
      dtype='str')
 Sold columns:
Index(['BuyerAgentAOR', 'ListAgentAOR', 'Flooring', 'ViewYN', 'WaterfrontYN',
       'BasementYN', 'PoolPrivateYN', 'OriginalListPrice', 'ListingKey',
       'CloseDate', 'ClosePrice', 'ListAgentFirstName', 'ListAgentLastName',
       'Latitude', 'Longitude', 'UnparsedAddress', 'PropertyType',
       'LivingArea', 'ListPrice', 'DaysOnMarket', 'ListOfficeName',
       'BuyerOfficeName', 'CoListOfficeName', 'ListAgentFullName',
       'CoListAgentFirstName', 'CoListAgentLastName', 'BuyerAgentMlsId',
       'BuyerAgentFirstName', 'BuyerAgentLastName', 'FireplacesTotal',
       'AssociationFeeFrequency', 'AboveGradeFinishedArea',
       'ListingKeyNumeric', 'MLSAreaMajor', 'TaxAnnualAmount',
       'CountyOrParish', 'MlsStatus', 'ElementarySchool', 'AttachedGarageYN',
       'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'StreetNumberNumeric',
       'ListingId', 'BathroomsTotalInteger', 'City', 'TaxYear',
       'BuildingAreaTotal', 'BedroomsTotal', 'ContractStatusChangeDate',
       'ElementarySchoolDistrict', 'CoBuyerAgentFirstName',
       'PurchaseContractDate', 'ListingContractDate', 'BelowGradeFinishedArea',
       'BusinessType', 'StateOrProvince', 'CoveredSpaces',
       'MiddleOrJuniorSchool', 'FireplaceYN', 'Stories', 'HighSchool',
       'Levels', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'AssociationFee', 'LotSizeSquareFeet', 'MiddleOrJuniorSchoolDistrict',
       'OriginatingSystemName', 'OriginatingSystemSubName'],
      dtype='str')

In [25]:
listings_df.shape

(5000, 81)

In [26]:
sold_df.shape

(19081, 79)